// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.
// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

function findtheDiff(s,t) {
    if(s.length === 0) return t;
    let lookup = {};
    for (let index = 0; index < s.length; index++) {
        let val = s.charAt(index);
        lookup[val] = (lookup[val]||0) + 1;
    }
    for (let index = 0; index < t.length; index++) {
        let val = t.charAt(index);
        if (lookup[val]) {
            lookup[val]--;
        } else {
            return val;
        }     
    }
}
//Alternate solution is getting Unicode values and getting character from difference of unicode value
console.log(findtheDiff("","t"))